/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.illud.freightgw.client.freight.api;

import com.illud.freightgw.client.freight.model.Company;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-09-18T10:06:28.627+05:30[Asia/Calcutta]")

@Api(value = "CompanyResource", description = "the CompanyResource API")
public interface CompanyResourceApi {

    @ApiOperation(value = "createCompany", nickname = "createCompanyUsingPOST", notes = "", response = Company.class, tags={ "company-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Company.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/companies",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<Company> createCompanyUsingPOST(@ApiParam(value = "company" ,required=true )  @Valid @RequestBody Company company);


    @ApiOperation(value = "deleteCompany", nickname = "deleteCompanyUsingDELETE", notes = "", tags={ "company-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/companies/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteCompanyUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getAllCompanies", nickname = "getAllCompaniesUsingGET", notes = "", response = Company.class, responseContainer = "List", tags={ "company-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Company.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/companies",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<Company>> getAllCompaniesUsingGET();


    @ApiOperation(value = "getCompany", nickname = "getCompanyUsingGET", notes = "", response = Company.class, tags={ "company-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Company.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/companies/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<Company> getCompanyUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "searchCompanies", nickname = "searchCompaniesUsingGET", notes = "", response = Company.class, responseContainer = "List", tags={ "company-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Company.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/_search/companies",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<Company>> searchCompaniesUsingGET(@NotNull @ApiParam(value = "query", required = true) @Valid @RequestParam(value = "query", required = true) String query);


    @ApiOperation(value = "updateCompany", nickname = "updateCompanyUsingPUT", notes = "", response = Company.class, tags={ "company-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Company.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/companies",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<Company> updateCompanyUsingPUT(@ApiParam(value = "company" ,required=true )  @Valid @RequestBody Company company);

}
