/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.illud.freightgw.client.freight.api;

import com.illud.freightgw.client.freight.model.Freight;
import com.illud.freightgw.client.freight.model.FreightDTO;
import java.util.List;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-10-29T13:04:19.756+05:30[Asia/Calcutta]")

@Api(value = "FreightResource", description = "the FreightResource API")
public interface FreightResourceApi {

    @ApiOperation(value = "assignVehicle", nickname = "assignVehicleUsingPOST", notes = "", response = FreightDTO.class, tags={ "freight-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = FreightDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/updatefreightandvehicleforfreightorvehicleid/{vehicleId}",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<FreightDTO> assignVehicleUsingPOST(@ApiParam(value = "vehicleId",required=true) @PathVariable("vehicleId") Long vehicleId,@ApiParam(value = "freightDTO" ,required=true )  @Valid @RequestBody FreightDTO freightDTO);


    @ApiOperation(value = "createFreightDTO", nickname = "createFreightDTOUsingPOST", notes = "", response = FreightDTO.class, tags={ "freight-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = FreightDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/convertToDto",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<FreightDTO> createFreightDTOUsingPOST(@ApiParam(value = "freight" ,required=true )  @Valid @RequestBody Freight freight);


    @ApiOperation(value = "createFreightDtoList", nickname = "createFreightDtoListUsingPOST", notes = "", response = FreightDTO.class, responseContainer = "List", tags={ "freight-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = FreightDTO.class, responseContainer = "List"),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/convertToList",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<List<FreightDTO>> createFreightDtoListUsingPOST(@ApiParam(value = "list" ,required=true )  @Valid @RequestBody List<Freight> freight);


    @ApiOperation(value = "createFreight", nickname = "createFreightUsingPOST", notes = "", response = FreightDTO.class, tags={ "freight-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = FreightDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/freights",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<FreightDTO> createFreightUsingPOST(@ApiParam(value = "freightDTO" ,required=true )  @Valid @RequestBody FreightDTO freightDTO);


    @ApiOperation(value = "deleteFreight", nickname = "deleteFreightUsingDELETE", notes = "", tags={ "freight-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/freights/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteFreightUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getAllFreights", nickname = "getAllFreightsUsingGET", notes = "", response = FreightDTO.class, responseContainer = "List", tags={ "freight-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = FreightDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/freights",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<FreightDTO>> getAllFreightsUsingGET(@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "getFreightByTrackingId", nickname = "getFreightByTrackingIdUsingGET", notes = "", response = FreightDTO.class, tags={ "freight-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = FreightDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/freight/{trackingId}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<FreightDTO> getFreightByTrackingIdUsingGET(@ApiParam(value = "trackingId",required=true) @PathVariable("trackingId") String trackingId);


    @ApiOperation(value = "getFreight", nickname = "getFreightUsingGET", notes = "", response = FreightDTO.class, tags={ "freight-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = FreightDTO.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/freights/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<FreightDTO> getFreightUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "searchFreights", nickname = "searchFreightsUsingGET", notes = "", response = FreightDTO.class, responseContainer = "List", tags={ "freight-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = FreightDTO.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/_search/freights",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<FreightDTO>> searchFreightsUsingGET(@NotNull @ApiParam(value = "query", required = true) @Valid @RequestParam(value = "query", required = true) String query,@ApiParam(value = "Page number of the requested page") @Valid @RequestParam(value = "page", required = false) Integer page,@ApiParam(value = "Size of a page") @Valid @RequestParam(value = "size", required = false) Integer size,@ApiParam(value = "Sorting criteria in the format: property(,asc|desc). Default sort order is ascending. Multiple sort criteria are supported.") @Valid @RequestParam(value = "sort", required = false) List<String> sort);


    @ApiOperation(value = "updateFreight", nickname = "updateFreightUsingPUT", notes = "", response = FreightDTO.class, tags={ "freight-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = FreightDTO.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/freights",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<FreightDTO> updateFreightUsingPUT(@ApiParam(value = "freightDTO" ,required=true )  @Valid @RequestBody FreightDTO freightDTO);

}
