/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.0.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.illud.freightgw.client.freight.api;

import com.illud.freightgw.client.freight.model.Vehicle;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-09-19T13:10:39.142+05:30[Asia/Calcutta]")

@Api(value = "VehicleResource", description = "the VehicleResource API")
public interface VehicleResourceApi {

    @ApiOperation(value = "createVehicle", nickname = "createVehicleUsingPOST", notes = "", response = Vehicle.class, tags={ "vehicle-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Vehicle.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/vehicles",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<Vehicle> createVehicleUsingPOST(@ApiParam(value = "vehicle" ,required=true )  @Valid @RequestBody Vehicle vehicle);


    @ApiOperation(value = "deleteVehicle", nickname = "deleteVehicleUsingDELETE", notes = "", tags={ "vehicle-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK"),
        @ApiResponse(code = 204, message = "No Content"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden") })
    @RequestMapping(value = "/api/vehicles/{id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deleteVehicleUsingDELETE(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "getAllVehicles", nickname = "getAllVehiclesUsingGET", notes = "", response = Vehicle.class, responseContainer = "List", tags={ "vehicle-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Vehicle.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/vehicles",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<Vehicle>> getAllVehiclesUsingGET();


    @ApiOperation(value = "getVehicle", nickname = "getVehicleUsingGET", notes = "", response = Vehicle.class, tags={ "vehicle-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Vehicle.class),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/vehicles/{id}",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<Vehicle> getVehicleUsingGET(@ApiParam(value = "id",required=true) @PathVariable("id") Long id);


    @ApiOperation(value = "searchVehicles", nickname = "searchVehiclesUsingGET", notes = "", response = Vehicle.class, responseContainer = "List", tags={ "vehicle-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Vehicle.class, responseContainer = "List"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/_search/vehicles",
        produces = "*/*", 
        method = RequestMethod.GET)
    ResponseEntity<List<Vehicle>> searchVehiclesUsingGET(@NotNull @ApiParam(value = "query", required = true) @Valid @RequestParam(value = "query", required = true) String query);


    @ApiOperation(value = "updateVehicle", nickname = "updateVehicleUsingPUT", notes = "", response = Vehicle.class, tags={ "vehicle-resource", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = Vehicle.class),
        @ApiResponse(code = 201, message = "Created"),
        @ApiResponse(code = 401, message = "Unauthorized"),
        @ApiResponse(code = 403, message = "Forbidden"),
        @ApiResponse(code = 404, message = "Not Found") })
    @RequestMapping(value = "/api/vehicles",
        produces = "*/*", 
        consumes = "application/json",
        method = RequestMethod.PUT)
    ResponseEntity<Vehicle> updateVehicleUsingPUT(@ApiParam(value = "vehicle" ,required=true )  @Valid @RequestBody Vehicle vehicle);

}
